clean: true

theme: fullwidth

output: docs
source_directory: Sources
readme: README.md

module: PathWrangler
swift_build_tool: spm
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/PathWrangler

author: ser.soft GmbH
author_url: https://sersoft.de
